### ISSUE TITLE
[!!] encodeSigHeader doesnt take into account chainID / BSC SLASHING MECHANISM IS NOT WORKING

### ISSUE THREAD

**Issue by Ezkerrox** [bnb-chain/bnc-cosmos-sdk#306]
## Summary of Bug 
 
In BSC sealHash is calculated taking into account Chain ID. However encodeSigHeader does not take into account chainID, meaning that sealHash will return an incorrect hash, thus ExtractSignerFromHeader() returns an invalid signer. In BSC header hash is Sealed including chainID, so encodeSigHeader() must include the chain ID.

## Steps to Reproduce
 
Brief example: Block 23188712 of BSC : Signer of block : 0x72b61c6014342d914470eC7aC2975bE345796c2b.
Block Header : {"parentHash":"0xa9c482b74a276389681eabff076b19bef53cae9b5e44f02224e70e3bfc4e9142","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","miner":"0x72b61c6014342d914470ec7ac2975be345796c2b","stateRoot":"0xacd5bca0bc33ed07cb35a635fa674e4ce06211ba201500564dd14dcdaf53e5a9","transactionsRoot":"0xcb374b870584bd587dec2e82af38924a5c0d5765913568434c50448856f97a2c","receiptsRoot":"0x6f2dc6ade8cf9422d62abd8e8386f20576a6b1f31cc00aa83dba140d183cff16","logsBloom":"0xfcfef2ce9d78d29fcbfefbff9dfdf3afb23eff54be7efe7ffdb47abcffdff35fff7bf5de80e257fc836eb97fab43eef33dc7b7ffdfb7fcebfb3df6efff7fecfef473d6fe31dcbcebf7ffeff957b6fbbc6d1efb7ebfddbd3bddfeffded78df79ef3ff9ffd4fd67fcfdfdfff3fecdeddefddadf6ef802b5feaf6f4debffbd7ff9b1fcffff73ceb76fddcfd5f73ffff61bed4be7fb59fe77baebb746f4bcefbdebb76df77fdfb8b73bd2ffcf763b33ff7a6cfeefd7e36f6ed275ffa7fff7fbb996ff33bfbdfe76f23bfecf1ffcfceff3fefbd57b5f5dbfd7fde75cffff77ffffa7feefdf7ddef66f7db77fffd47efa6e5bf55f7fef3ebfbbdf3b1fe77f93ffacedf","difficulty":"0x2","number":"0x161d4e8","gasLimit":"0x7355c0c","gasUsed":"0x2134d60","timestamp":"0x6378bdd7","extraData":"0xd883010111846765746888676f312e31392e32856c696e757800000040fc9c67c61ee4a053e5ec524393cb2608e7a1b0de9a91f880095cd7bfc009b8e0ab5de96c2085a484239f38ca437bc805d2df9b88ea2a9a2a1ce9f5ab6005ae3464b17601","mixHash":"0x0000000000000000000000000000000000000000000000000000000000000000","nonce":"0x0000000000000000","baseFeePerGas":null,"hash":"0x8b6eeece6cedbb23038e7e5c2ce647fbdffa04972247d60a7564e81897e8bc30"}

Deducted signer by ExtractSignerFromHeader() : 0x5eE85a5cff0621D8E4734fdf434cd5E49E276697 which is INCORRECT.

Here is how sealHash is calculated in BSC:
func encodeSigHeader(w io.Writer, header *types.Header, chainId *big.Int) {
	err := rlp.Encode(w, []interface{}{
		**chainId**,
		header.ParentHash,
		header.UncleHash,
		header.Coinbase,
....
Chain id is first element. However seal hash here is calculated in this way:
func encodeSigHeader(w io.Writer, header *Header) {
	err := rlp.Encode(w, []interface{}{
		header.ParentHash,
		header.UncleHash,
		header.Coinbase,
		header.Root,
...
Chain id is missing in the first element.

This has a REALLY big impact because this function is used for checking a bsc slashing evidence. Here you need to send two headers, and this function will always return incorrect signers, and even if the evidence is valid (The two headers are signed by the same validator), it will return the error: "message":"The signers of two block headers are not the same", and throw away the evidence.

Files to be changed: header.go, encodeSigHeader must accept chainID as a parameter and rlp Encode must have it in the first place.
____
#### For Admin Use
 - [ ] Not duplicate issue
 - [ ] Appropriate labels applied
 - [ ] Appropriate contributors tagged
 - [ ] Contributor assigned/self-assigned

**Comment by brilliant-lx** [comment]
thx, we are aware as it, since it is a same issue as https://github.com/bnb-chain/bsc/issues/1200.
track in #1200, close this one.
